### ISSUE TITLE
crash editing date field

### ISSUE THREAD

**Issue by sshupe** [HeidiSQL/HeidiSQL#1024]
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/4595214/bugreport.txt)

## Steps to reproduce this issue

1. Step 1; Run query
2. Step 2; click on date field
3. Then I get... error occurred in the application (attached bug report)

## Current behavior

Tried to edit date field in grid to update table, heidisql.exe throws an exception .
This occurs with a query with multiple tables joined,
not on single table queries. 
## Expected behavior

expected inline editing of date data.
## Environment

* **HeidiSQL version:** 
11.0.0.5919
* **Database system and version:** 
Aurora RDS 1.19.5 (MySQL 5.6.10)
  
* **Operating system:** 
OS Name:	Microsoft Windows 10 Home
Version	10.0.18362 Build 18362

**Comment by sshupe** [comment]
forgot to add
database version: Aurora RDS 1.19.5 (MySQL)

**Comment by ansgarbecker** [comment]
Should be fixed in the next build.

**Comment by sshupe** [comment]
No longer get the crash, but when I select the date field,
edit commands do not work. Unable to paste or enter data from keyboard

**Comment by ansgarbecker** [comment]
This is very normal in a joined table result - HeidiSQL only offers editing when the column's origin table could be determined. If the result comes from two or more tables, it is practically impossible to compose the right UPDATE command automatically.

**Comment by sshupe** [comment]
It used to work. I still have a machine with 10.03 on it, it works there.
I was using it often to clean up bad table data. For now I'll put a copy of 10.03.5771 on
my other machine for this query. any known problems with running two versions of HeidiSQL
on the same machine?

**Comment by ansgarbecker** [comment]
> any known problems with running two versions of HeidiSQL on the same machine?

Not relevant I believe.
But v10.3 may have some difference in the underlying detection of the origin tables. v11.0 is the current release, and I'm sure that one behaves similar to the nighlty build. Anyway, this is not a consequence of the fix for this crash here. I guess we should reactivate #1025 in that case.
