### ISSUE TITLE
MySQL 8.0 adds invisible indices

### ISSUE THREAD

**Issue by Madjosz** [HeidiSQL/HeidiSQL#1388]
**Is your feature request related to a problem? Please describe.**
MySQL 8.0 introducted [invisible indices](https://dev.mysql.com/doc/refman/8.0/en/invisible-indexes.html). These are indices which are present and will be filled during `INSERT`/`UPDATE` but are not used for query optimization (e.g. to "test drop" an index and see the performance impacts without actually dropping the index)
Currently this feature is not supported at all in HeidiSQL (checked with latest nightly build 11.3.0.6317 64-bit).

`SHOW CREATE TABLE` on MySQL Server 8.0.24 gives the following query for a table with hidden indices:

    CREATE TABLE `table` (
      `id` INTEGER NOT NULL,
      `v1` INTEGER NOT NULL DEFAULT 0,
      `v2` INTEGER NOT NULL DEFAULT 0,
      PRIMARY KEY (`id`),
      KEY `kv1` (`v1`),
      KEY `kv2` (`v2`) /*!80000 INVISIBLE */
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

In "CREATE code" tab in the table editor this comment is not visible at all.

**Describe the solution you'd like**
* Support this feature in the "Indexes" tab to see if an index is visible/invisible.
* Provide a UI functionality to change this "invisible" flag.
* Don't hide comments in "CREATE code" tab

**Describe alternatives you've considered**
For now it is only possible to view/change this state directly by using the "Query" tab and write a proper MySQL query by hand.

    ALTER TABLE `table` ALTER INDEX `kv1` INVISIBLE;

**Additional context**
#128 may be connected to parts of this issue.

**Comment by ansgarbecker** [comment]
MariaDB has a similar feature called "ignored" indexes. I am on the way to support both invisible and ignored in a new "Visibility" marker of HeidiSQL's index editor:

<img width="884" height="153" alt="Image" src="https://github.com/user-attachments/assets/7fc8ab89-44e4-4bce-abcb-9d33ed0f2d6e" />

After editing that flag, HeidiSQL adds the INVISIBLE or VISIBLE flag to the index code it does with other index related changes:
```sql
ALTER TABLE `invisi` DROP INDEX `ktitle`, ADD INDEX `ktitle` (`title`) INVISIBLE;
```

Now there is an issue with that in MySQL and (!) MariaDB: That combined `ALTER TABLE ... DROP + ADD` syntax seems to ignore the modified INVISIBLE (or VISIBLE) flag. So the index is saved, no error is thrown, but the index is still visible or invisible like before!

I would like someone to test this as well, as I have the feeling I am doing something wrong here.

**Comment by Madjosz** [comment]
I would assume that dropping and adding the index again would actually rebuilt it so could lead to severe performance impacts.

**Comment by ansgarbecker** [comment]
Yes, acknowledged. I am just reading about the newer `ALTER INDEX` command, which seems to only support changing VISIBLE flag. All other stuff, like column subparts, comment and `USING BTREE` and such must still be done with a `ALTER TABLE ... DROP INDEX xyz, ADD INDEX xy... ` command. For both MySQL and MariaDB.

**Comment by ansgarbecker** [comment]
Should be working in the next build. MySQL supported with `ALTER TABLE x ALTER INDEX y VISIBLE/INVISIBLE` now, and MariaDB with its own clause `IGNORED/NOT IGNORED`.

@Madjosz would you perhaps give it a test with the new build? Thank you anyway for your feedback!

**Comment by Madjosz** [comment]
Just tested it with HeidiSQL 12.16.0.7267 (64-bit) on a MySQL server 8.0.36 and setting an invisible index to visible via UI lead to the following two queries:

<img width="657" height="61" alt="Image" src="https://github.com/user-attachments/assets/9c00e243-ce19-40d8-85d7-3fa7baabf099" />

"CREATE code" tab still does not show the `/*INVISIBLE*/` comment.

Creating a new index as invisible does ignore the invisible part and only creates a visible index.

PRIMARY KEY columns allow the option to set the visibility which will result in
```
ALTER TABLE `invisibleindex`
    ALTER INDEX `PRIMARY` INVISIBLE;
/* SQL Error (3522): A primary key index cannot be invisible */
```

But otherwise thx for implementing. Keep up the good work!

**Comment by ansgarbecker** [comment]
Thanks for your feedback.

Indeed the CREATE code tab misses that, because the normal drop + add syntax for ALTER did not do what I would have expected. Same reason for why the CREATE code is missing it. This just means that invisible indexes need an alteration after creating a new table. I would leave this as it is now, for not adding more special quirks for this otherwise simple feature. Primary keys throw a well readable error when trying to save, so I tend to also leave this is as it is.
