### ISSUE TITLE
Scrolling horizontally with mouse wheel broken

### ISSUE THREAD

**Issue by chrysler5798** [HeidiSQL/HeidiSQL#355]
Hello !

## Steps to reproduce this issue

To reproduce this issue you need a mouse with a horizontal scroll wheel. Or emulate it but I don't know how.

1. Go to a table or whatever window that needs a horizontal scrollbar
2. Scroll horizontally with the horizontal mouse scroll wheel

## Current behavior

It displays a new scrollbar and it doesn't scroll anyways.
![2018-09-26_11-14-52](https://user-images.githubusercontent.com/7657777/46070215-828ab000-c17d-11e8-82bc-f4a17f84aac5.gif)

## Expected behavior

Scrolling horizontally.

## Environment

* **HeidiSQL version:** 9.5.0.5293 (64 Bit)
* **Operating system:** Windows v10.0

**Comment by ansgarbecker** [comment]
Are you sure this is only happening in HeidiSQL, not in other programs as well?

**Comment by chrysler5798** [comment]
@ansgarbecker no it seems like some software support it :
- Google Chrome
- Firefox
- IntelliJ / Android Studio
- FileZilla

But others have the same behavior as HeidiSQL, creating another scrollbar which doesn't work: 
- Notepad++
(I don't have any other example for the moment)

So I would say it's not broken but not supported.
Thanks for your answer !

**Comment by ansgarbecker** [comment]
Could you please test whether horizontal scrolling is broken in the query editor also? And in some more places, eg. the database tree on the left side. That way I can probably narrow down the problem to the component(s) in which that happens.

**Comment by chrysler5798** [comment]
I tried some places and the horizontal scrolling works : 
* In the text editor
* In the query editor
![2018-10-11_10-23-35](https://user-images.githubusercontent.com/7657777/46790946-49873980-cd40-11e8-8b9c-d3111c3faa72.gif)


It doesn't work : 
* In the database tree
* In the table data tab, host tab, variables tab...

**Comment by leon-v** [comment]
I have had this issue for a while as well, I had a feeling it was to do with the Logitech software and the way it implements H scroll.

Query editor does work, Seems like it too fast though. And the scroll bar changes between theme colour and basic windows colour while scrolling.

It has been a pet peev of mine for a while. (don't want to detract from how awesome Heidi is generally though)

**Comment by rNianios** [comment]
This is still happening on 10.1.0.5464 (64 bit)
OS is Windows 10 1809

It's really strange that the actual scroll bars moves but not the table!

**Comment by VilleSimola** [comment]
I have this problem with my laptop's touchpad. My scrollbar doesn't move at all though, so the problems might be related or not. When I slide the touhcpad with two fingers it scrolls every view in HeidSQL 10.3. nicely vertically but not horizontally. This function works well everywhere else.

**Comment by mz1909** [comment]
The issue still exists. Just bought a Mouse with second scroll-wheel (Logitech MX Master) for database-purposes and it doesn't work.

Heidi SQL 11.0.0.5919 (64 Bit)
The scrollbar moves but not the page (like on the example by chrysler from Sep 2018. If I use Shift + normal scrollwheel it scrolls horizontally - so the funktion generally works, but it seems not linked correctly to the horizontal-scroll-wheel-action.

Heidi SQL 11.0.0.5974 (64 Bit)
In the latest version nothing happens at all - not even a scrollbar moving.

If a horizontal scroll would do the same as shift + normal scroll it would be fine!


Many thanks in advance for your help!


PS: Win10 1909 build 18363.815 (64 bit) was used for testing.

**Comment by sadachi** [comment]
Completely same as mz1919 with ver.11.0.0.5989

I am using  Logitech MX Monster 3

**Comment by ansgarbecker** [comment]
Potentially related: https://github.com/JAM-Software/Virtual-TreeView/issues/953

I updated the VirtualTree sources on end of May, and once again a few weeks ago. Could someone with a capable mouse please test whether the current nightly build changes anything here?

**Comment by chrysler5798** [comment]
I can't make it work in build 11.0.0.6050.
What's more, the weird scrollbar that was showing (see GIF on my first message) doesn't show anymore.

**Comment by gribeiro20** [comment]
any news?
still facing this issue, it's really annoying. I own a Logitech mx master 3 and the horizontal scroll works all around, even in vscode which is a little buggy. However in Heidi doesn't work at all, the behavior that I experience is the same as @mz1909

**Comment by leon-v** [comment]
Bump.
I'm still experiencing the same issue as described in this report.
I also have an MX Master, but only the 2S.
Maybe @ansgarbecker  can shed any light on this ?

**Comment by sadachi** [comment]
Today I installed development version 6265, and found H scroll wheel no longer works any more..
Even scroll bar does not move.

**Comment by KENNYSOFT** [comment]
Still v11.3, with MX Master.

**Comment by hwebb** [comment]
Still an issue with V 12.0.0.6468 64Bit. Using MX Master 3S.
I will donate once this issue is solved.

**Comment by ansgarbecker** [comment]
Please update to the latest build, which has the latest modifications for VirtualTree and a compiler upgrade.

**Comment by hwebb** [comment]
Still no luck here unfortunately. I've even added HeidiSQL to the list of apps on the mouse software, but it doesn't change anything. If I change the action to Zoom in and out or navigate between tabs, the action is working well, just not horizontal scroll. Same behavior as OP.

**Comment by dankoman30** [comment]
bump

**Comment by srotak5** [comment]
I have this issue with my logitech mx master 2s, please please fix it, or rather implement it

**Comment by Boshentz** [comment]
I can confirm that in W10, Heidi 12.5.0.6677 and logitech mx master 3s this issue still exists

**Comment by Errox** [comment]
I can confirm that in heidi 12.5.0.6684 and the logitech mx master 3s this issue still exists. Running Windows 11

**Comment by er1z** [comment]
W10, HSQL 12.5.0.6677, MX Master 3, newest drivers and still occurs.

**Comment by borhanuddin** [comment]
I'm using MX Master 3s with Logi Options+ software. Fixed this issue by creating HeidiSQL profile and change horizontal action to **Keyboard shortcut** and apply **scroll up** with **Ctrl + Right** and **scroll down** with **Ctrl + Left**. I hope this help.

![Screenshot 2023-11-27 090626](https://github.com/HeidiSQL/HeidiSQL/assets/4537394/19f114b6-3389-49b3-9cbd-a3006348ec4b)

**Comment by okkebal** [comment]
Same problem here, but my mouse does not have fancy settings like logitech. 

In almost all software you can hold down shift an use the mousewheel to scroll horizontally. This does not work in Heidi either. This way you do need a special mouse to see if this works: Just hold down shift and use the scrollwheel.

**Comment by ansgarbecker** [comment]
> In almost all software you can hold down shift an use the mousewheel to scroll horizontally. This does not work in Heidi either. 

<kbd>Shift+MouseWheel</kbd> definitely works for me here. Please try again.
As a side note, <kbd>Ctrl+MouseWheel</kbd> is used to zoom in and out in the grids.

**Comment by okkebal** [comment]
You 

> > In almost all software you can hold down shift an use the mousewheel to scroll horizontally. This does not work in Heidi either.
> 
> Shift+MouseWheel definitely works for me here. Please try again. As a side note, Ctrl+MouseWheel is used to zoom in and out in the grids.

You are right. I am wrong! It does work. Very strange on trying again it does seem to work. Shift + scrollwheel works for horizontal scrolling, but the mouse scrollwheel does not... So how about I donate the ergonomic mouse that I use so you can debug this issue? I use this mouse. Its an egonomic mouse with a wire. Its really a great mouse: https://www.deluxworld.com/en-pro-detail-m618xsu.html The side support is magnetically detachable so you don't have to use that. If you send me your shipping adress I will donate this mouse to the cause.... (would be nice if you remove my "donate" button for that). This mouse is really a game changer for me. I understand its no guarantee that you can 100% fix this issue... I'm a developer myself.

**Comment by ansgarbecker** [comment]
@okkebal please do not send me a mouse. I already own an MX Master 3S from Logitech, and I can confirm the horizontal scroll wheel issue. Using the Logi Options+ tool, I can assign <kbd>Ctrl+Left</kbd> and <kbd>Ctrl+Right</kbd> to fix that, like @borhanuddin already explained. And yes, for other mouses without such a support tool the issue persists.
This is definitely an issue in VirtualTreeView, the component used for grids and trees. It does not handle a horizontal wheel scroll correctly. I will try to compare what the SynEdit component does correctly (the SQL editors) - the wheel works there.

**Comment by ansgarbecker** [comment]
I found a fix for this in `VirtualTrees.BaseTree.pas` - seems that `TScrollInfo.nTrackPos` is always 0 on the horizontal scrollbar. Potentially a bug in the underlying Windows API, not sure. However, the wheel delta from the Windows message (`TWMScroll.Pos`) seems to work correctly.

**Comment by ansgarbecker** [comment]
Here's a proof that the fix works:

![grid-horizontal-scroll-wheel](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/9c8924f4-3b0b-4ab3-8412-ee8b18b78e9a)

**Comment by KENNYSOFT** [comment]
Glad to see fixed in 12.7, Thanks!!!

**Comment by IntegratedTurnover** [comment]
The horizontal scroll issue is back in 12.14.0.7165 on Windows 11 Pro 25H2. I don't know which version brought the bug back, or if 12.7 ever worked on my machine. Scrolling in the data tab, database tab, and table tab only moves the scrollbar and not the view.

Not sure if this issue is still a concern due to the impending codebase migration in V13.

**Comment by ansgarbecker** [comment]
You may give it a test drive in v13 - a preview release is [on the download page](https://www.heidisql.com/download.php#preview-windows-v13).

**Comment by IntegratedTurnover** [comment]
I believe I correctly installed the test drive version, the titlebar says 12.14.1.1, I was expecting it to say v13.0 or v12.99 or some such.

Regardless, the bug is still present in the test drive version; but instead of the heidi scrollbar moving, an older looking windows default style scrollbar appears and moves while the view remains stationary.

Edit: Tested the native linux version just now, horizontal scroll works properly on Ubuntu. Looks like this is specific to Windows

**Comment by ansgarbecker** [comment]
My Logitech MX mouse currently scrolls nothing horizontally with that thumbs wheel, at least not in HeidiSQL, both in the current 12.14 release and not in the 13 preview (yes, the internal versioning is wrong).
To get a fix for future updates I posted a ticket in the Lazarus tracker: https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/41985
