### ISSUE TITLE
1215: “Cannot add foreign key constraint” Problem

### ISSUE THREAD

**Issue by ulaskayalar** [HeidiSQL/HeidiSQL#50]
I have tried many methods, considering that this error is from column mismatch, but the problem is that the line format is not set as default. The line format should automatically be dynamic when exporting a foreign key. 

I've been through this for 1 day. When I realized that I could not fix it on HeidiSQL, I switched to the Navicat program and assigned a foreign key and observed that it was active without problems. The reason that it was active was that the line format was set to DYNAMIC.

_I use Google Translate..._

**Comment by ansgarbecker** [comment]
Please follow the issue template the next time.

Some questions, as this is a bit unclear to me:
* HeidiSQL version, MySQL/MariaDB version?
* When exactly did you see this error message?
* What row format did the table have when it was not DYNAMIC?

**Comment by ulaskayalar** [comment]
1- HeidiSQL version, MySQL/MariaDB version?
1-Answer: 
I do not know the old version because I downloaded the new version, but I am using **MYSQL**.


2-When exactly did you see this error message?
2-Answer: When associating foreign keys between tables. I tried all sorts of solutions, but everything seemed right.


3-What row format did the table have when it was not DYNAMIC?
3-Answer: **DEFAULT**.


I'm sorry I could not keep up with the sketch.

**Comment by ansgarbecker** [comment]
DEFAULT row format is the same as DYNAMIC, isn't it?
You can check the row format when you fire a `SHOW TABLE STATUS` in the relevant database.

> I do not know the old version because I downloaded the new version, but I am using MYSQL.

I assume you are on HeidiSQL 9.5, right? That's important man, please just provide such details here when reporting bugs.
And you need to provide the exact MySQL version here, otherwise I'm probably spending too much time for a bug which was fixed at some point.

**Comment by ulaskayalar** [comment]
I do not know if the default and dynamic line formats are the same, but the problem is solved when dynamic is preferred instead of default.

I experienced the problem in MYSQL 9.4

**Comment by ansgarbecker** [comment]
Ok, then we have just a requirement, not an issue in Heidi. Thanks for your quick feedback!

**Comment by ulaskayalar** [comment]
I have tried Mysql versions 5.7 and 5.6 separately and I have observed that heidisql is problematic. The problem is not in dynamic row format but I try to associate foreign key in Navicat program and it works fine. In the same way, I try in HeidiSQL, there is a problem. In the meantime, I use google cloud servers.

**Comment by ansgarbecker** [comment]
I still have problems in understanding what I can do here. Is there some concrete `ALTER` query which HeidiSQL should run before storing a foreign key?
This ticket is missing some conrete details, something beyond "_Navicat can do it, but HeidiSQL can't_"

**Comment by lukinhaspm** [comment]
Hello, it's no make senses... @ulaskayalar , can you provide the tables/database structures and what we need to do to simulate this? I work with Heidi and other MySQL tools, I can try use this tools to test too...

**Comment by ulaskayalar** [comment]
The problem is to associate foreign keys from different tables. Other programs already know that this is a bug, so they automatically fix it for beginners. You need to associate your identity (SEPARATOR) and other foreign key independently of the tables. Associating MSSQL Diagram is an example of this.

I would like to give detailed information and I would like to answer your questions, but my English is weak.

**Comment by lukinhaspm** [comment]
I think this is conceptual.
You can connect columns of the same type and size, one of which is the primary key of the parent table.
Avoid using text columns for this, you will gain in performance and organization of tables.
I do not see why associating two primary keys between them, I use FKs a long time and I have no problems, I wish I could simulate this in Heidi with your table structure. Send some pics or .sqls
