### ISSUE TITLE
"The system cannot find the path specified" when typing a query

### ISSUE THREAD

**Issue by rg54** [HeidiSQL/HeidiSQL#815]
## Steps to reproduce this issue

1. Install HeidiSQL
2. Connect to a MariaDB instance
3. Go to "Query" tab and start typing query

## Current behavior

After some seconds, the following message appears :
"Cannot create file "C:\Users\xxxxxxxx\Application Data\HeidiSQL\Backups\query-tab-2019-11-25_10-33-46-451.sql". The system cannot find the path specified"

this behavior is described here : https://social.technet.microsoft.com/Forums/windows/en-US/1c3e806a-0412-4591-b94a-ac2b71074b28/forum-faqwhy-application-data-folder-is-not-accessible?forum=w7itprogeneral

But I don't know why I cannot reproduce it on Windows 7.
Maybe it's an optional security policy which is applied by my company system administrators ? I can't check with them easily (working in a very big company, and I don't have direct contacts for that)

## Expected behavior

As I understand it, HeidiSQL would normally create a folder "HeidiSQL\Backups" in "C:\Users\xxxxxxxx\AppData\Roaming" (which is the target of alias C:\Users\xxxxxxxx\Application Data\")

But it can't do this, because this particular alias allow to access to a subfolder via alias, but not to  list the aliased folder in himself :

- in explorer, entering "%appdata%\Microsoft" in address bar is opening folder "C:\Users\xxxxxxxx\Application Data\Microsoft" (which is actually "C:\Users\xxxxxxxx\AppData\Roaming\Microsoft" folder)

- the same with "%appdata%" is giving an "access denied" error

And a capture with Process Monitor when reproducing the bug in HeidiSQL confirms this

## Possible solution

Instead of listing folder "C:\Users\xxxxxxxx\Application Data" to look for "HeidiSQL" folder, trying to create it directly. that seems to work with PowerShell :  
`New-Item -Type Directory $env:APPDATA\HeidiSQL`

## Environment

* **HeidiSQL version:** 
10.2.0.5599 (not tested on nightly build, because the affected server doesn't have access to Internet, so I cannot download the build from "check for updates")

* **Database system and version:** 
MariaDB, but probably occurs with others RDBMS too

* **Operating system:** 
Windows Server 2016
Also tested on Windows 7, not reproduced

**Comment by ansgarbecker** [comment]
Please update to v10.3, and report back if that makes a difference. I applied some minor changes to this tab store/restore logic, so maybe we're fine here, although I guess not.

**Comment by rg54** [comment]
With 10.3.0.5771, behavior is quite different : I have an error directly when connecting on a DB :
![image](https://user-images.githubusercontent.com/30940681/71108993-99735300-21c4-11ea-97c1-535da7929077.png)

And I don't have one any more when I start typing in Query tab. But I still have an exception when closing the window.
and no folder "C:\Users\xxxxxxxx\Application Data\HeidiSQL\" created, obviously.

**Comment by ansgarbecker** [comment]
Thanks for your report and screenshot. May I assume you were running HeidiSQL on Windows 10 there? And is there a folder `C:\Users\xyz\Application Data\` on your disk?
This folder should normally be as follows on Win10: `C:\Users\xyz\AppData\Roaming\`
I wonder why the base folder is wrongly detected on your system.
I just pushed a change which uses the newer KNOWNFOLDERID constants for detecting that AppData\Roaming folder. Probably this helps.

**Comment by rg54** [comment]
I've download the last nightly EXE, and replaced the one in HeidiSQL install folder on my VM (on Windows Server 2016)

And I still have the exact same error message than with 10.3.0.5771 :
![image](https://user-images.githubusercontent.com/30940681/75906693-5cc00b00-5e47-11ea-9b7c-1e994c7d554c.png)

When I'm trying to access directly to folder C:\Users\xxxx\Application Data\, I also have an "Access is denied" error.
It's OK for C:\Users\xxx\AppData\Roaming\ but it does not contain any "HeidiSQL" folder

**Comment by ansgarbecker** [comment]
Yes, HeidiSQL detects the folder `C:\Users\xxxx\Application Data`, and tries to create a file there, which fails. Reading from it also fails. The directory simply does not exist. Your system points to that wrong non existent folder, with the `FOLDERID_RoamingAppData` id. 
You can test it by firing an `echo %appdata%` in a `cmd.exe` shell:
![grafik](https://user-images.githubusercontent.com/7986591/75920679-1fb44280-5e60-11ea-8d88-4b1211aba3b7.png)
This is also taken from a Win2016 server by the way.

**Comment by rg54** [comment]
Here is the result of this command, it's pointing to the old folder in my case :
![image](https://user-images.githubusercontent.com/30940681/75986487-72d4d680-5eee-11ea-8dc8-4c2388c189d7.png)

**Comment by ansgarbecker** [comment]
Maybe this points to some error happened during the OS installation. I have no clue how to really solve that, this looks like an issue for which Microsoft is responsible. As a workaround, you could create that `Application Data` folder in your user folder.

**Comment by rg54** [comment]
That's right, I've checked on another server in different project context, and I've the same thing as you (Roaming folder).

And Application Data folder already exists as a kind of symlink to Roaming, but it's not possible to access it directly ("access denied" even in explorer), as explained before.
t's only possible to access to subfolders via "Application Data" symlink.

Maybe it's linked to VM template customizations done by client infrastructure team.

I've no time to investigate on this for instance

But I close this ticket, because as I understand, everything is OK in application side now (with good variable values)

Thanks for investigation.
